name: Build FluidNC Firmware (ESP32 All Binaries)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build all firmware
        run: pio run

      - name: Build LittleFS filesystem
        run: pio run -t buildfs
        continue-on-error: true

      - name: List built files
        run: ls -R .pio/build

      - name: Upload binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: true
          files: |
            .pio/build/*/firmware*.bin
            .pio/build/*/bootloader*.bin
            .pio/build/*/partitions*.bin
            .pio/build/*/littlefs*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
