name: FluidNC Versioned Release

on:
  push:
    tags:
      - 'v*'   # contoh: v1.0.0, v1.2.3, dst.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release version (e.g. v1.0.0)'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    # Build semua environment ESP32 klasik (exclude S3 karena error i2s)
    - name: Build ESP32 environments
      run: |
        pio run -e wifi -e bt -e noradio

    - name: Build LittleFS (optional)
      run: |
        pio run -t buildfs -e wifi -e bt -e noradio
      continue-on-error: true

    - name: List outputs
      run: ls -lh .pio/build/*/

    # 🔹 Package semua .bin ke dalam satu ZIP (folder env ikut masuk)
    - name: Package BIN files
      run: |
        mkdir -p release
        zip -9 -r release/fluidnc-binaries-${{ github.ref_name }}.zip .pio/build/*/*.bin

    # 🔹 Copy file lain (ELF, MAP) ke folder release
    - name: Collect other artifacts
      run: |
        cp .pio/build/*/*.elf release/ 2>/dev/null || true
        cp .pio/build/*/*.map release/ 2>/dev/null || true

    # 🔹 Upload ke Release sesuai tag
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        overwrite: true
        files: |
          release/fluidnc-binaries-${{ github.ref_name }}.zip
          release/*.elf
          release/*.map
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
