name: FluidNC Release Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    # Build semua env (tanpa S3 dulu)
    - name: Build all firmware
      run: pio run -e wifi -e bt -e noradio

    - name: Build LittleFS filesystem
      run: pio run -t buildfs -e wifi -e bt -e noradio
      continue-on-error: true

    - name: List build outputs
      run: ls -lh .pio/build/*/

    # 🔹 Kumpulkan semua .bin ke dalam satu ZIP
    - name: Package BIN files
      run: |
        mkdir -p release
        zip -j release/fluidnc-binaries.zip .pio/build/*/*.bin

    # 🔹 Copy file lain (misalnya ELF, MAP) ke folder release
    - name: Collect other artifacts
      run: |
        cp .pio/build/*/*.elf release/ || true
        cp .pio/build/*/*.map release/ || true

    # 🔹 Upload ke Release
    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        draft: false
        prerelease: false
        overwrite: true
        files: |
          release/fluidnc-binaries.zip
          release/*.elf
          release/*.map
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
